import express from 'express';
import dotenv from 'dotenv';
import { createShopifyGraph } from './server/shopify-client.js';
import { registerStockRoutes } from './server/stock-routes.js';
import { registerSalesRoutes } from './server/sales-routes.js';
import { registerLocationUpdaterRoutes } from './server/location-updater-routes.js';
import { LOCATION_FIELDS, LOCATION_SCHEMA } from './public/location-fields.js';
dotenv.config();
const app=express(),PORT=process.env.PORT||3000,SHOP=process.env.SHOPIFY_SHOP,TOKEN=process.env.SHOPIFY_ACCESS_TOKEN,API=process.env.SHOPIFY_API_VERSION||'2024-07',SHOPIFYQL_API=process.env.SHOPIFYQL_API_VERSION||'2025-10';
if(!SHOP||!TOKEN){console.error('Set SHOPIFY_SHOP & SHOPIFY_ACCESS_TOKEN in Render environment variables.');process.exit(1);}
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, X-Requested-With');res.setHeader('Access-Control-Max-Age','86400');if(req.method==='OPTIONS')return res.sendStatus(204);next();});
app.use(express.json({limit:'20mb'}));
app.use('/vendor/bwip-js',express.static('node_modules/bwip-js/dist'));
app.use(express.static('public',{setHeaders:res=>res.setHeader('Cache-Control','no-cache')}));
const shopifyGraph=createShopifyGraph({shop:SHOP,token:TOKEN,apiVersion:API});
registerStockRoutes(app,{shopifyGraph,shop:SHOP,apiVersion:API});
registerSalesRoutes(app,{shop:SHOP,apiVersion:API,shopifyqlApiVersion:SHOPIFYQL_API});
registerLocationUpdaterRoutes(app,{shopifyGraph});
app.get('/health',(_req,res)=>res.json({ok:true,app:'Head Happy Stock Control + Locations',version:'1.4.0',locationSchema:LOCATION_SCHEMA,commit:process.env.RENDER_GIT_COMMIT||null,shop:SHOP,apiVersion:API,shopifyqlApiVersion:SHOPIFYQL_API,salesSource:'shopifyql.inventory.inventory_units_sold',yesterdaySalesEndpoint:'/api/shopify-yesterday-sales.json',stockLocationFields:Object.fromEntries(LOCATION_FIELDS.map(f=>[f.column,`Variant metafield ${f.namespace}.${f.key}`])),updaterFeatures:{ownerType:'PRODUCTVARIANT',productLocationFallback:false,displaySlots:2,lod:'Independent (LOD) suffix on each display',blankProtection:'Blank values require explicit Clear confirmation'},labelStation:{page:'/label-station.html',paper:'40x25mm',barcode:'Code 128',locationListEndpoint:'/api/labels/locations',locationProductsEndpoint:'/api/labels/location-products'},cors:true,time:new Date().toISOString()}));
app.listen(PORT,()=>console.log(`Head Happy Stock Control + Locations listening on http://localhost:${PORT}`));
