import test from 'node:test';
import assert from 'node:assert/strict';
import {LOCATION_FIELDS,LOCATION_SCHEMA,parseDisplay,displayValue,locationKey,normaliseLookupRow} from '../public/location-fields.js';
import {locationRow,findLocationMatches,findExactLocationContents,findLocationContents,listLocationLabels,expireLocationSearchCache,VARIANT_FIELDS} from '../server/location-search.js';
import {registerLocationUpdaterRoutes} from '../server/location-updater-routes.js';
import {registerStockRoutes,baseRow,stockRows,STOCK_COLUMNS,STOCK_QUERY,STOCK_BY_LOCATION_QUERY} from '../server/stock-routes.js';
const id=n=>`gid://shopify/ProductVariant/${n}`;
function fixture(){const p={id:'gid://shopify/Product/10',title:'Test item',status:'ACTIVE',handle:'test-item',vendor:'Test',tags:[],displayLoc:{value:'POISON PARENT'},loc2:{value:'POISON BULK'}};return [
 {id:id(101),title:'Blue',sku:'SKU_BLUE',barcode:'012345',price:'5.00',inventoryQuantity:7,product:p,displayLoc:{value:'Cabinet 7'},displayLoc2:{value:'Window 2 (LOD)'},quickLoc:{value:'MC1 D1'},loc2:{value:'Blue 9'}},
 {id:id(102),title:'Red',sku:'SKU_RED',barcode:'012346',price:'6.00',inventoryQuantity:3,product:p,displayLoc:{value:'Cabinet 8 (LOD)'},displayLoc2:{value:'Till'},quickLoc:{value:'MC1 D10'},loc2:{value:'Blue 8'}},
 {id:id(103),title:'Default Title',sku:'SKU_SINGLE',barcode:'012347',price:'4.00',inventoryQuantity:2,product:{...p,id:'gid://shopify/Product/11',title:'Single'},displayLoc:{value:'Window 2'},displayLoc2:{value:'Window 2'},quickLoc:null,loc2:null}
 ];}
function graphFor(rows){const calls=[];const graph=async(query,variables={})=>{calls.push({query,variables});if(query.includes('metafieldsSet')){const v=rows.find(v=>v.id===variables.id),f=LOCATION_FIELDS.find(f=>f.key===variables.key&&f.namespace===variables.namespace);if(!v||!f)return {metafieldsSet:{userErrors:[{message:'Bad variant or key'}]}};v[f.alias]={value:variables.value};return {metafieldsSet:{userErrors:[]}};}if(query.includes('metafieldsDelete')){for(const m of variables.metafields){const v=rows.find(v=>v.id===m.ownerId),f=LOCATION_FIELDS.find(f=>f.key===m.key&&f.namespace===m.namespace);if(v&&f)v[f.alias]=null;}return {metafieldsDelete:{userErrors:[],deletedMetafields:variables.metafields}};}if(query.includes('nodes(ids:'))return {nodes:variables.ids.map(i=>rows.find(v=>v.id===i)||null)};return {productVariants:{nodes:rows,pageInfo:{hasNextPage:false,endCursor:null}}};};return {graph,calls};}
function appFor(graph,stock=false){const routes=new Map(),app={post:(p,f)=>routes.set(`POST ${p}`,f),get:(p,f)=>routes.set(`GET ${p}`,f)};if(stock)registerStockRoutes(app,{shopifyGraph:graph,shop:'test.myshopify.com',apiVersion:'2025-10'});else registerLocationUpdaterRoutes(app,{shopifyGraph:graph});const request=async(method,path,body={},query={})=>{const res={code:200,headers:{},status(n){this.code=n;return this;},setHeader(k,v){this.headers[k]=v;},json(data){this.data=data;return this;},send(data){this.data=data;return this;}};const handler=routes.get(`${method} ${path}`);assert.ok(handler,`Route exists: ${method} ${path}`);await handler({body,query},res);return res;};return {request,routes};}
test('the four-field contract has distinct variant display keys',()=>{assert.equal(LOCATION_FIELDS.length,4);assert.equal(new Set(LOCATION_FIELDS.map(f=>f.namespace+'.'+f.key)).size,4);assert.equal(LOCATION_FIELDS[1].key,'display_loc_2');assert.equal(LOCATION_FIELDS[1].column,'DisplayLocation2');assert.match(LOCATION_SCHEMA,/display2/);});
test('LOD is independent and exact physical matching does not conflate drawer names',()=>{assert.deepEqual(parseDisplay('Window 2 (LOD)'),{base:'Window 2',lod:true});assert.equal(parseDisplay('Cabinet 7').lod,false);assert.equal(displayValue('Window 2',true),'Window 2 (LOD)');assert.equal(displayValue('Cabinet 7',false),'Cabinet 7');assert.throws(()=>displayValue('',true));assert.equal(locationKey(' Window  2 (LOD) '),'window 2');assert.notEqual(locationKey('MC1 D1'),locationKey('MC1 D10'));});
test('rows never inherit any location from a parent product, including default variants',()=>{const v=fixture()[0];v.displayLoc=null;v.displayLoc2=null;const row=locationRow(v);assert.equal(row.currentDisplayLoc,'');assert.equal(row.currentDisplayLoc2,'');assert.equal(row.currentLoc2,'Blue 9');const single=fixture()[2];single.displayLoc=null;assert.equal(locationRow(single).currentDisplayLoc,'');assert.equal(locationRow(single).variantTitle,'');});
test('normalisation keeps a blank variant title blank and includes Display 2',()=>{const row=normaliseLookupRow({id:id(1),title:'Parent title',variantTitle:'',currentDisplayLoc2:'Till'});assert.equal(row.variantTitle,'');assert.equal(row.currentDisplayLoc2,'Till');assert.equal(normaliseLookupRow({id:id(2)}, {currentDisplayLoc2:'Window 2'}).currentDisplayLoc2,'Window 2');});
test('either display finds a variant once, independent LOD counts are returned',async()=>{expireLocationSearchCache();const {graph}=graphFor(fixture());const r=await findExactLocationContents(graph,'Window 2');assert.equal(r.count,2);assert.deepEqual(r.rows.map(x=>x.id).sort(),[id(101),id(103)]);assert.equal(r.stockTotal,9);assert.equal(r.lod1Count,0);assert.equal(r.lod2Count,1);assert.deepEqual(r.rows.find(x=>x.id===id(103)).matches,['DISPLAY','DISPLAY2']);});
test('location catalogue deduplicates repeated codes and stock totals across fields',async()=>{expireLocationSearchCache();const {graph}=graphFor(fixture());const r=await listLocationLabels(graph),window=r.locations.find(l=>l.code==='Window 2');assert.deepEqual(window.types,['DISPLAY','DISPLAY2']);assert.equal(window.variantCount,2);assert.equal(window.stockTotal,9);assert.ok(!r.locations.some(l=>l.code.includes('POISON')));});
test('exact bin search differs from area contains search',async()=>{expireLocationSearchCache();const {graph}=graphFor(fixture());assert.equal((await findExactLocationContents(graph,'MC1 D1')).count,1);assert.equal((await findLocationContents(graph,'MC1 D1')).count,2);assert.equal((await findExactLocationContents(graph,'0')).count,0);});
test('exact SKU/barcode selection excludes fuzzy sibling results',async()=>{expireLocationSearchCache();const {graph}=graphFor(fixture());const r=await findLocationMatches(graph,'SKU_BLUE');assert.equal(r.hits.length,1);assert.equal(r.hits[0].id,id(101));assert.equal((await findLocationMatches(graph,'12345')).hits[0].id,id(101));assert.equal((await findLocationMatches(graph,'SKU_')).hits.length,3);});
test('every field writes only the selected variant and never siblings',async()=>{expireLocationSearchCache();const data=fixture(),before=structuredClone(data[1]),{graph,calls}=graphFor(data),{request}=appFor(graph);for(const f of LOCATION_FIELDS){const r=await request('POST',f.endpoint,{variantId:id(101),[f.valueKey]:'NEW '+f.name});assert.equal(r.code,200);assert.equal(r.data.success,true);assert.equal(data[0][f.alias].value,'NEW '+f.name);assert.deepEqual(data[1],before);}assert.equal(calls.filter(c=>c.query.includes('metafieldsSet')).length,4);assert.equal(data[0].product.displayLoc.value,'POISON PARENT');});
test('parent IDs, absent IDs, blanks and orphan LOD are rejected before writes',async()=>{const {graph,calls}=graphFor(fixture()),{request}=appFor(graph);for(const variantId of ['gid://shopify/Product/10','',undefined])assert.equal((await request('POST','/update-display-loc-2',{variantId,displayLoc2Value:'Window 2'})).code,400);for(const displayLoc2Value of ['', ' ', 'LOD','Window\n2'])assert.equal((await request('POST','/update-display-loc-2',{variantId:id(101),displayLoc2Value})).code,400);assert.equal(calls.length,0);});
test('clearing Display 2 explicitly cannot erase Display 1 or bulk',async()=>{const data=fixture(),{graph}=graphFor(data),{request}=appFor(graph);assert.equal((await request('POST','/clear-variant-location',{variantId:id(101),field:'display2'})).code,400);const r=await request('POST','/clear-variant-location',{variantId:id(101),field:'display2',confirmClear:true});assert.equal(r.code,200);assert.equal(data[0].displayLoc2,null);assert.equal(data[0].displayLoc.value,'Cabinet 7');assert.equal(data[0].loc2.value,'Blue 9');});
test('save invalidates the location cache so the new Display 2 is immediately searchable',async()=>{expireLocationSearchCache();const data=fixture(),{graph}=graphFor(data),{request}=appFor(graph);await listLocationLabels(graph);await request('POST','/update-display-loc-2',{variantId:id(101),displayLoc2Value:'New Window'});assert.equal((await findExactLocationContents(graph,'New Window')).count,1);assert.equal((await findExactLocationContents(graph,'Window 2')).count,1);});
test('single and multi lookup response shapes both include second display',async()=>{expireLocationSearchCache();const {graph}=graphFor(fixture()),{request}=appFor(graph);const one=await request('POST','/lookup-variant',{search:'SKU_BLUE'});assert.equal(one.data.currentDisplayLoc2,'Window 2 (LOD)');assert.equal(one.data.variant.id,id(101));const many=await request('POST','/lookup-variant',{search:'SKU_'});assert.equal(many.data.variants.length,3);assert.ok(many.data.variants.every(v=>'currentDisplayLoc2' in v));});
test('label refresh reads actual variant IDs without performing mutations',async()=>{const {graph,calls}=graphFor(fixture()),{request}=appFor(graph);const r=await request('POST','/api/labels/variants',{variantIds:[id(101),id(102)]});assert.equal(r.data.rows.length,2);assert.equal(r.data.rows[0].currentDisplayLoc2,'Window 2 (LOD)');assert.equal(calls.some(c=>c.query.includes('mutation')),false);assert.equal((await request('POST','/api/labels/variants',{variantIds:['gid://shopify/Product/10']})).code,400);});
test('stock row and CSV retain old columns and append DisplayLocation2',async()=>{const source=fixture()[0],row=baseRow(source);assert.equal(row.DisplayLocation,'Cabinet 7');assert.equal(row.DisplayLocation2,'Window 2 (LOD)');assert.equal(row.ShelfLocation,'MC1 D1');assert.equal(row.LOC2,'Blue 9');assert.equal(STOCK_COLUMNS.indexOf('DisplayLocation'),9);assert.equal(STOCK_COLUMNS.at(-1),'DisplayLocation2');const {graph}=graphFor(fixture()),{request}=appFor(graph,true),r=await request('GET','/api/shopify-stock.csv');assert.equal(r.code,200);assert.match(r.data.split('\n')[0],/"Handle","DisplayLocation2"$/);assert.match(r.data,/Window 2 \(LOD\)/);});
test('both stock JSON formats include Display 2 on every exported variant',async()=>{const rows=fixture();for(const v of rows)v.inventoryItem={id:'gid://shopify/InventoryItem/1',tracked:true,inventoryLevels:{nodes:[{quantities:[{name:'available',quantity:5}],location:{id:'L1',name:'Shop'}}]}};const {graph}=graphFor(rows);for(const byLocation of [false,true]){const output=await stockRows(graph,{status:'ACTIVE'},byLocation);assert.equal(output.length,3);assert.equal(output[0].DisplayLocation2,'Window 2 (LOD)');}});
test('all new GraphQL reads place the four metafields on variants, not product owners',()=>{for(const query of [VARIANT_FIELDS,STOCK_QUERY,STOCK_BY_LOCATION_QUERY]){assert.match(query,/display_loc_2/);assert.doesNotMatch(query,/product\s*\{[^}]*metafield/);}});
test('catalogue follows every page and refuses a non-advancing cursor',async()=>{expireLocationSearchCache();let n=0;const v=fixture();const graph=async()=>({productVariants:{nodes:[v[n++]],pageInfo:n===1?{hasNextPage:true,endCursor:'next'}:{hasNextPage:false,endCursor:null}}});assert.equal((await listLocationLabels(graph)).locations.find(x=>x.code==='Till').variantCount,1);expireLocationSearchCache();await assert.rejects(()=>listLocationLabels(async()=>({productVariants:{nodes:[],pageInfo:{hasNextPage:true,endCursor:null}}})),/did not advance/);});
